### ISSUE TITLE
Install and configure DHCP server

### ISSUE THREAD

**Issue by matthew-dawson** [Ashtoruin/pibernetes#3]
The master node requires a DHCP server be exposed so that worker nodes can acquire IP addresses.

- [x] Configure static IP address for eth0 interface
- [x] Install and configure DHCP server to provide IP addresses on the internal network (eth0)
- [x] Tests confirming the DHCP server is installed and configured as intended.

[DHCP guide for future reference](http://www.noveldevices.co.uk/rp-dhcp-server)

**Comment by matthew-dawson** [comment]
Re: Tests confirming DHCP server functionality:

- [ ] A DHCP client request results in a response from the dhcp server containing an IP address and subnet definition with the specified range.

**Comment by Ashtoruin** [comment]
Testing:

Validate router ip:
ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+'

create virtual interface:
sudo dhclient eth0:1

validate virtual interface ip (plus router):
ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+'

**Comment by Ashtoruin** [comment]
Better ip add:
`ip` -f inet addr show eth0:1 | grep -Po 'inet \K[\d.]+'`
